server-ip=127.0.0.1
server-port=25566
query.port=25566
enable-query=false
enable-rcon=false
online-mode=false
enforce-secure-profile=false
white-list=true
enforce-whitelist=true
max-players=6
view-distance=2
simulation-distance=2
level-name=world
pause-when-empty-seconds=0
motd=Isolated Solid Gold Stairs tests
